import type { GameMeta } from "@/types/games";

export const GAMES: GameMeta[] = [
	{
		id: "connect4",
		name: "コネクト4",
		description: "交互にコマを落として縦横斜めに4つ並べたら勝ち！",
		imageSrc: "/games/thumbnail_connect4.png",
		localPath: "/connect4",
		onlinePath: "/connect4/newRoom",
		isAvailable: true,
		tags: ["2人用", "パズル"],
	},
	{
		id: "reversi",
		name: "オセロ",
		description: "相手の石を挟んでひっくり返し、最後に多い方が勝ち。",
		imageSrc: "/games/thumbnail_reversi.png",
		localPath: "/reversi",
		// onlinePath: "/reversi/newRoom",
		isAvailable: true,
		tags: ["2人用", "陣取り"],
	},
	{
		id: "gomoku",
		name: "五目並べ",
		description: "先に5つ並べた方が勝ちのシンプルな思考ゲーム。",
		imageSrc: "/globe.svg",
		localPath: "/gomoku",
		onlinePath: "/gomoku/newRoom",
		isAvailable: false,
		tags: ["2人用", "パズル"],
	},
	{
		id: "tic-tac-toe",
		name: "三目並べ",
		description: "3×3のマスで○×を並べるカジュアル対戦。",
		imageSrc: "/next.svg",
		localPath: "/tic-tac-toe",
		onlinePath: "/tic-tac-toe/newRoom",
		isAvailable: false,
		tags: ["2人用", "ライト"],
	},
	{
		id: "chess",
		name: "チェス",
		description: "世界的定番の戦略ボードゲーム。キングを詰めろ。",
		imageSrc: "/vercel.svg",
		localPath: "/chess",
		onlinePath: "/chess/newRoom",
		isAvailable: false,
		tags: ["2人用", "戦略"],
	},
	{
		id: "checkers",
		name: "チェッカー",
		description: "相手の駒を飛び越えて取り合うシンプル戦略。",
		imageSrc: "/file.svg",
		localPath: "/checkers",
		onlinePath: "/checkers/newRoom",
		isAvailable: false,
		tags: ["2人用", "カジュアル"],
	},
	{
		id: "shogi",
		name: "将棋",
		description: "取った駒を打てるのが特徴の日本の伝統戦略ゲーム。",
		imageSrc: "/globe.svg",
		localPath: "/shogi",
		onlinePath: "/shogi/newRoom",
		isAvailable: false,
		tags: ["2人用", "戦略"],
	},
	{
		id: "go",
		name: "囲碁",
		description: "地を取り合う奥深い陣取りゲーム。",
		imageSrc: "/window.svg",
		localPath: "/go",
		onlinePath: "/go/newRoom",
		isAvailable: false,
		tags: ["2人用", "陣取り"],
	},
	{
		id: "backgammon",
		name: "バックギャモン",
		description: "ダイス運と戦略で駒をベアオフするレースゲーム。",
		imageSrc: "/next.svg",
		localPath: "/backgammon",
		onlinePath: "/backgammon/newRoom",
		isAvailable: false,
		tags: ["2人用", "レース"],
	},
	{
		id: "battleship",
		name: "海戦ゲーム",
		description: "相手の艦隊位置を推理して撃沈を狙う推測ゲーム。",
		imageSrc: "/vercel.svg",
		localPath: "/battleship",
		onlinePath: "/battleship/newRoom",
		isAvailable: false,
		tags: ["2人用", "推理"],
	},
];
